version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: jphacks
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - jphacks-volume:/var/lib/mysql
    restart: always

  server:
    build: ./server
    ports:
      - 8000:8000
    volumes:
      - ./server:/src/server

volumes:
  jphacks-volume: