version: '3'
services:
  server:
    build: ./server
    ports:
      - 8000:8000
    volumes:
      - ./server:/src/server
  db:
    image: mysql:8.0
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: jphacks
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - jphacks-volume:/var/lib/mysql
    restart: always

volumes:
  jphacks-volume: